#
#       MAKEFILE FOR RAND "LA" LINE-ACCESS I/O PACKAGE
#
ARFLAGS = -r
# CFLAGS = -O -I. -I../ff3 -I../include
CFLAGS = -I. -I../ff3 -I../include -g

ALL=libla.a
SRCS=   laabort.c laadv.c   laalign.c lablank.c labreak.c labsize.c \
	lacfile.c laclose.c ladeb.c   laerr.c   lafrpl.c \
	laint.c   lalcnt.c  lalcol.c  lalcopy.c laldel.c  lalflush.c \
	lalget.c  lalink.c  lalins.c  lalpnt.c  lalrpl.c  lalrsize.c \
	lalseek.c lalwsize.c laopen.c laother.c

OBJS=   laabort.o laadv.o   laalign.o lablank.o labreak.o labsize.o \
	lacfile.o laclose.o ladeb.o   laerr.o   lafrpl.o \
	laint.o   lalcnt.o  lalcol.o  lalcopy.o laldel.o  lalflush.o \
	lalget.o  lalink.o  lalins.o  lalpnt.o  lalrpl.o  lalrsize.o \
	lalseek.o lalwsize.o laopen.o laother.o

$(ALL) : $(OBJS)
	$(AR) $(ARFLAGS) $@ $(OBJS)

clean:
	rm -f $(OBJS) $(ALL)  ,* .e?1 .e?1.* core *.bak *.BAK *~ \#*

depend:
	makedepend -- $(CFLAGS) -- $(SRCS)

# DO NOT DELETE THIS LINE -- make depend depends on it.

laabort.o: la.local.h ../include/c_env.h ../include/localenv.h
laabort.o: /usr/include/sys/types.h /usr/include/features.h
laabort.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laabort.o: /usr/include/gnu/types.h /usr/include/time.h
laabort.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
laabort.o: /usr/include/endian.h /usr/include/bytesex.h
laabort.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
laabort.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
laabort.o: /usr/include/_G_config.h
laabort.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
laabort.o: /usr/include/stdio_lim.h /usr/include/limits.h
laabort.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
laabort.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
laadv.o: la.local.h ../include/c_env.h ../include/localenv.h
laadv.o: /usr/include/sys/types.h /usr/include/features.h
laadv.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laadv.o: /usr/include/gnu/types.h /usr/include/time.h
laadv.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
laadv.o: /usr/include/endian.h /usr/include/bytesex.h
laadv.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h ../ff3/ff.h
laadv.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h
laadv.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
laadv.o: /usr/include/stdio_lim.h /usr/include/limits.h
laadv.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
laadv.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
laalign.o: la.local.h ../include/c_env.h ../include/localenv.h
laalign.o: /usr/include/sys/types.h /usr/include/features.h
laalign.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laalign.o: /usr/include/gnu/types.h /usr/include/time.h
laalign.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
laalign.o: /usr/include/endian.h /usr/include/bytesex.h
laalign.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
laalign.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
laalign.o: /usr/include/_G_config.h
laalign.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
laalign.o: /usr/include/stdio_lim.h /usr/include/limits.h
laalign.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
laalign.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
lablank.o: la.local.h ../include/c_env.h ../include/localenv.h
lablank.o: /usr/include/sys/types.h /usr/include/features.h
lablank.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lablank.o: /usr/include/gnu/types.h /usr/include/time.h
lablank.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
lablank.o: /usr/include/endian.h /usr/include/bytesex.h
lablank.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
lablank.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
lablank.o: /usr/include/_G_config.h
lablank.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
lablank.o: /usr/include/stdio_lim.h /usr/include/limits.h
lablank.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
lablank.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
labreak.o: la.local.h ../include/c_env.h ../include/localenv.h
labreak.o: /usr/include/sys/types.h /usr/include/features.h
labreak.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
labreak.o: /usr/include/gnu/types.h /usr/include/time.h
labreak.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
labreak.o: /usr/include/endian.h /usr/include/bytesex.h
labreak.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
labreak.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
labreak.o: /usr/include/_G_config.h
labreak.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
labreak.o: /usr/include/stdio_lim.h /usr/include/limits.h
labreak.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
labreak.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
labsize.o: la.local.h ../include/c_env.h ../include/localenv.h
labsize.o: /usr/include/sys/types.h /usr/include/features.h
labsize.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
labsize.o: /usr/include/gnu/types.h /usr/include/time.h
labsize.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
labsize.o: /usr/include/endian.h /usr/include/bytesex.h
labsize.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
labsize.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
labsize.o: /usr/include/_G_config.h
labsize.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
labsize.o: /usr/include/stdio_lim.h /usr/include/limits.h
labsize.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
labsize.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
lacfile.o: la.local.h ../include/c_env.h ../include/localenv.h
lacfile.o: /usr/include/sys/types.h /usr/include/features.h
lacfile.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lacfile.o: /usr/include/gnu/types.h /usr/include/time.h
lacfile.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
lacfile.o: /usr/include/endian.h /usr/include/bytesex.h
lacfile.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
lacfile.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
lacfile.o: /usr/include/_G_config.h
lacfile.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
lacfile.o: /usr/include/stdio_lim.h /usr/include/limits.h
lacfile.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
lacfile.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
laclose.o: la.local.h ../include/c_env.h ../include/localenv.h
laclose.o: /usr/include/sys/types.h /usr/include/features.h
laclose.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laclose.o: /usr/include/gnu/types.h /usr/include/time.h
laclose.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
laclose.o: /usr/include/endian.h /usr/include/bytesex.h
laclose.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
laclose.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
laclose.o: /usr/include/_G_config.h
laclose.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
laclose.o: /usr/include/stdio_lim.h /usr/include/limits.h
laclose.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
laclose.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
ladeb.o: la.local.h ../include/c_env.h ../include/localenv.h
ladeb.o: /usr/include/sys/types.h /usr/include/features.h
ladeb.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
ladeb.o: /usr/include/gnu/types.h /usr/include/time.h
ladeb.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
ladeb.o: /usr/include/endian.h /usr/include/bytesex.h
ladeb.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h ../ff3/ff.h
ladeb.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h
ladeb.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
ladeb.o: /usr/include/stdio_lim.h /usr/include/limits.h
ladeb.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
ladeb.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
laerr.o: la.local.h ../include/c_env.h ../include/localenv.h
laerr.o: /usr/include/sys/types.h /usr/include/features.h
laerr.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laerr.o: /usr/include/gnu/types.h /usr/include/time.h
laerr.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
laerr.o: /usr/include/endian.h /usr/include/bytesex.h
laerr.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h ../ff3/ff.h
laerr.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h
laerr.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
laerr.o: /usr/include/stdio_lim.h /usr/include/limits.h
laerr.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
laerr.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
lafrpl.o: la.local.h ../include/c_env.h ../include/localenv.h
lafrpl.o: /usr/include/sys/types.h /usr/include/features.h
lafrpl.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lafrpl.o: /usr/include/gnu/types.h /usr/include/time.h
lafrpl.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
lafrpl.o: /usr/include/endian.h /usr/include/bytesex.h
lafrpl.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
lafrpl.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
lafrpl.o: /usr/include/_G_config.h
lafrpl.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
lafrpl.o: /usr/include/stdio_lim.h /usr/include/limits.h
lafrpl.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
lafrpl.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
lalcnt.o: la.local.h ../include/c_env.h ../include/localenv.h
lalcnt.o: /usr/include/sys/types.h /usr/include/features.h
lalcnt.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalcnt.o: /usr/include/gnu/types.h /usr/include/time.h
lalcnt.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
lalcnt.o: /usr/include/endian.h /usr/include/bytesex.h
lalcnt.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
lalcnt.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
lalcnt.o: /usr/include/_G_config.h
lalcnt.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
lalcnt.o: /usr/include/stdio_lim.h /usr/include/limits.h
lalcnt.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
lalcnt.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
lalcol.o: la.local.h ../include/c_env.h ../include/localenv.h
lalcol.o: /usr/include/sys/types.h /usr/include/features.h
lalcol.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalcol.o: /usr/include/gnu/types.h /usr/include/time.h
lalcol.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
lalcol.o: /usr/include/endian.h /usr/include/bytesex.h
lalcol.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
lalcol.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
lalcol.o: /usr/include/_G_config.h
lalcol.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
lalcol.o: /usr/include/stdio_lim.h /usr/include/limits.h
lalcol.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
lalcol.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
lalcopy.o: la.local.h ../include/c_env.h ../include/localenv.h
lalcopy.o: /usr/include/sys/types.h /usr/include/features.h
lalcopy.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalcopy.o: /usr/include/gnu/types.h /usr/include/time.h
lalcopy.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
lalcopy.o: /usr/include/endian.h /usr/include/bytesex.h
lalcopy.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
lalcopy.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
lalcopy.o: /usr/include/_G_config.h
lalcopy.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
lalcopy.o: /usr/include/stdio_lim.h /usr/include/limits.h
lalcopy.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
lalcopy.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
laldel.o: la.local.h ../include/c_env.h ../include/localenv.h
laldel.o: /usr/include/sys/types.h /usr/include/features.h
laldel.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laldel.o: /usr/include/gnu/types.h /usr/include/time.h
laldel.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
laldel.o: /usr/include/endian.h /usr/include/bytesex.h
laldel.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
laldel.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
laldel.o: /usr/include/_G_config.h
laldel.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
laldel.o: /usr/include/stdio_lim.h /usr/include/limits.h
laldel.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
laldel.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
lalflush.o: la.local.h ../include/c_env.h ../include/localenv.h
lalflush.o: /usr/include/sys/types.h /usr/include/features.h
lalflush.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalflush.o: /usr/include/gnu/types.h /usr/include/time.h
lalflush.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
lalflush.o: /usr/include/endian.h /usr/include/bytesex.h
lalflush.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
lalflush.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
lalflush.o: /usr/include/_G_config.h
lalflush.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
lalflush.o: /usr/include/stdio_lim.h /usr/include/limits.h
lalflush.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
lalflush.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
lalflush.o: /usr/include/errno.h /usr/include/errnos.h
lalflush.o: /usr/include/linux/errno.h /usr/include/asm/errno.h
lalflush.o: /usr/include/signal.h /usr/include/sigset.h /usr/include/signum.h
lalflush.o: /usr/include/sigaction.h /usr/include/sigcontext.h
lalflush.o: /usr/include/asm/sigcontext.h
lalget.o: la.local.h ../include/c_env.h ../include/localenv.h
lalget.o: /usr/include/sys/types.h /usr/include/features.h
lalget.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalget.o: /usr/include/gnu/types.h /usr/include/time.h
lalget.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
lalget.o: /usr/include/endian.h /usr/include/bytesex.h
lalget.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
lalget.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
lalget.o: /usr/include/_G_config.h
lalget.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
lalget.o: /usr/include/stdio_lim.h /usr/include/limits.h
lalget.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
lalget.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
lalink.o: la.local.h ../include/c_env.h ../include/localenv.h
lalink.o: /usr/include/sys/types.h /usr/include/features.h
lalink.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalink.o: /usr/include/gnu/types.h /usr/include/time.h
lalink.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
lalink.o: /usr/include/endian.h /usr/include/bytesex.h
lalink.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
lalink.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
lalink.o: /usr/include/_G_config.h
lalink.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
lalink.o: /usr/include/stdio_lim.h /usr/include/limits.h
lalink.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
lalink.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
lalins.o: la.local.h ../include/c_env.h ../include/localenv.h
lalins.o: /usr/include/sys/types.h /usr/include/features.h
lalins.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalins.o: /usr/include/gnu/types.h /usr/include/time.h
lalins.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
lalins.o: /usr/include/endian.h /usr/include/bytesex.h
lalins.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
lalins.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
lalins.o: /usr/include/_G_config.h
lalins.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
lalins.o: /usr/include/stdio_lim.h /usr/include/limits.h
lalins.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
lalins.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
lalpnt.o: la.local.h ../include/c_env.h ../include/localenv.h
lalpnt.o: /usr/include/sys/types.h /usr/include/features.h
lalpnt.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalpnt.o: /usr/include/gnu/types.h /usr/include/time.h
lalpnt.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
lalpnt.o: /usr/include/endian.h /usr/include/bytesex.h
lalpnt.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
lalpnt.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
lalpnt.o: /usr/include/_G_config.h
lalpnt.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
lalpnt.o: /usr/include/stdio_lim.h /usr/include/limits.h
lalpnt.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
lalpnt.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
lalrpl.o: la.local.h ../include/c_env.h ../include/localenv.h
lalrpl.o: /usr/include/sys/types.h /usr/include/features.h
lalrpl.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalrpl.o: /usr/include/gnu/types.h /usr/include/time.h
lalrpl.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
lalrpl.o: /usr/include/endian.h /usr/include/bytesex.h
lalrpl.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
lalrpl.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
lalrpl.o: /usr/include/_G_config.h
lalrpl.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
lalrpl.o: /usr/include/stdio_lim.h /usr/include/limits.h
lalrpl.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
lalrpl.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
lalrsize.o: la.local.h ../include/c_env.h ../include/localenv.h
lalrsize.o: /usr/include/sys/types.h /usr/include/features.h
lalrsize.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalrsize.o: /usr/include/gnu/types.h /usr/include/time.h
lalrsize.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
lalrsize.o: /usr/include/endian.h /usr/include/bytesex.h
lalrsize.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
lalrsize.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
lalrsize.o: /usr/include/_G_config.h
lalrsize.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
lalrsize.o: /usr/include/stdio_lim.h /usr/include/limits.h
lalrsize.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
lalrsize.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
lalseek.o: la.local.h ../include/c_env.h ../include/localenv.h
lalseek.o: /usr/include/sys/types.h /usr/include/features.h
lalseek.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalseek.o: /usr/include/gnu/types.h /usr/include/time.h
lalseek.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
lalseek.o: /usr/include/endian.h /usr/include/bytesex.h
lalseek.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
lalseek.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
lalseek.o: /usr/include/_G_config.h
lalseek.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
lalseek.o: /usr/include/stdio_lim.h /usr/include/limits.h
lalseek.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
lalseek.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
lalwsize.o: la.local.h ../include/c_env.h ../include/localenv.h
lalwsize.o: /usr/include/sys/types.h /usr/include/features.h
lalwsize.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalwsize.o: /usr/include/gnu/types.h /usr/include/time.h
lalwsize.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
lalwsize.o: /usr/include/endian.h /usr/include/bytesex.h
lalwsize.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
lalwsize.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
lalwsize.o: /usr/include/_G_config.h
lalwsize.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
lalwsize.o: /usr/include/stdio_lim.h /usr/include/limits.h
lalwsize.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
lalwsize.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
laopen.o: la.local.h ../include/c_env.h ../include/localenv.h
laopen.o: /usr/include/sys/types.h /usr/include/features.h
laopen.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laopen.o: /usr/include/gnu/types.h /usr/include/time.h
laopen.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
laopen.o: /usr/include/endian.h /usr/include/bytesex.h
laopen.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
laopen.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
laopen.o: /usr/include/_G_config.h
laopen.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
laopen.o: /usr/include/stdio_lim.h /usr/include/limits.h
laopen.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
laopen.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
laopen.o: /usr/include/sys/stat.h /usr/include/statbuf.h
laother.o: la.local.h ../include/c_env.h ../include/localenv.h
laother.o: /usr/include/sys/types.h /usr/include/features.h
laother.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laother.o: /usr/include/gnu/types.h /usr/include/time.h
laother.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stddef.h
laother.o: /usr/include/endian.h /usr/include/bytesex.h
laother.o: /usr/include/sys/select.h /usr/include/selectbits.h la.h
laother.o: ../ff3/ff.h /usr/include/stdio.h /usr/include/libio.h
laother.o: /usr/include/_G_config.h
laother.o: /usr/lib/gcc-lib/i386-redhat-linux/2.7.2.3/include/stdarg.h
laother.o: /usr/include/stdio_lim.h /usr/include/limits.h
laother.o: /usr/include/posix1_lim.h /usr/include/local_lim.h
laother.o: /usr/include/linux/limits.h /usr/include/posix2_lim.h
