#
#       MAKEFILE FOR RAND "LA" LINE-ACCESS I/O PACKAGE
#
ARFLAGS = -r
# CFLAGS = -O -I. -I../ff3 -I../include
CFLAGS = -I. -I../ff3 -I../include -g

ALL=libla.a
SRCS=   laabort.c laadv.c   laalign.c lablank.c labreak.c labsize.c \
	lacfile.c laclose.c ladeb.c   laerr.c   lafrpl.c \
	laint.c   lalcnt.c  lalcol.c  lalcopy.c laldel.c  lalflush.c \
	lalget.c  lalink.c  lalins.c  lalpnt.c  lalrpl.c  lalrsize.c \
	lalseek.c lalwsize.c laopen.c laother.c

OBJS=   laabort.o laadv.o   laalign.o lablank.o labreak.o labsize.o \
	lacfile.o laclose.o ladeb.o   laerr.o   lafrpl.o \
	laint.o   lalcnt.o  lalcol.o  lalcopy.o laldel.o  lalflush.o \
	lalget.o  lalink.o  lalins.o  lalpnt.o  lalrpl.o  lalrsize.o \
	lalseek.o lalwsize.o laopen.o laother.o

$(ALL) : $(OBJS)
	$(AR) $(ARFLAGS) $@ $(OBJS)

clean:
	rm -f $(OBJS) $(ALL)  ,* .e?1 .e?1.* core *.bak *.BAK *~ \#*

depend:
	makedepend -- $(CFLAGS) -- $(SRCS)

# DO NOT DELETE THIS LINE -- make depend depends on it.

laabort.o: la.local.h ../include/c_env.h ../include/localenv.h
laabort.o: /usr/include/stdio.h /usr/include/features.h
laabort.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laabort.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
laabort.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
laabort.o: /usr/include/bits/types.h /usr/include/libio.h
laabort.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
laabort.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
laabort.o: /usr/include/endian.h /usr/include/bits/endian.h
laabort.o: /usr/include/sys/select.h /usr/include/bits/select.h
laabort.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
laabort.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
laabort.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
laabort.o: /usr/include/bits/posix2_lim.h
laadv.o: la.local.h ../include/c_env.h ../include/localenv.h
laadv.o: /usr/include/stdio.h /usr/include/features.h
laadv.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laadv.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
laadv.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
laadv.o: /usr/include/bits/types.h /usr/include/libio.h
laadv.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
laadv.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
laadv.o: /usr/include/endian.h /usr/include/bits/endian.h
laadv.o: /usr/include/sys/select.h /usr/include/bits/select.h
laadv.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
laadv.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
laadv.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
laadv.o: /usr/include/bits/posix2_lim.h
laalign.o: la.local.h ../include/c_env.h ../include/localenv.h
laalign.o: /usr/include/stdio.h /usr/include/features.h
laalign.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laalign.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
laalign.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
laalign.o: /usr/include/bits/types.h /usr/include/libio.h
laalign.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
laalign.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
laalign.o: /usr/include/endian.h /usr/include/bits/endian.h
laalign.o: /usr/include/sys/select.h /usr/include/bits/select.h
laalign.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
laalign.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
laalign.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
laalign.o: /usr/include/bits/posix2_lim.h
lablank.o: la.local.h ../include/c_env.h ../include/localenv.h
lablank.o: /usr/include/stdio.h /usr/include/features.h
lablank.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lablank.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
lablank.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
lablank.o: /usr/include/bits/types.h /usr/include/libio.h
lablank.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
lablank.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
lablank.o: /usr/include/endian.h /usr/include/bits/endian.h
lablank.o: /usr/include/sys/select.h /usr/include/bits/select.h
lablank.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
lablank.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
lablank.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
lablank.o: /usr/include/bits/posix2_lim.h
labreak.o: la.local.h ../include/c_env.h ../include/localenv.h
labreak.o: /usr/include/stdio.h /usr/include/features.h
labreak.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
labreak.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
labreak.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
labreak.o: /usr/include/bits/types.h /usr/include/libio.h
labreak.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
labreak.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
labreak.o: /usr/include/endian.h /usr/include/bits/endian.h
labreak.o: /usr/include/sys/select.h /usr/include/bits/select.h
labreak.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
labreak.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
labreak.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
labreak.o: /usr/include/bits/posix2_lim.h
labsize.o: la.local.h ../include/c_env.h ../include/localenv.h
labsize.o: /usr/include/stdio.h /usr/include/features.h
labsize.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
labsize.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
labsize.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
labsize.o: /usr/include/bits/types.h /usr/include/libio.h
labsize.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
labsize.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
labsize.o: /usr/include/endian.h /usr/include/bits/endian.h
labsize.o: /usr/include/sys/select.h /usr/include/bits/select.h
labsize.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
labsize.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
labsize.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
labsize.o: /usr/include/bits/posix2_lim.h
lacfile.o: la.local.h ../include/c_env.h ../include/localenv.h
lacfile.o: /usr/include/stdio.h /usr/include/features.h
lacfile.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lacfile.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
lacfile.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
lacfile.o: /usr/include/bits/types.h /usr/include/libio.h
lacfile.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
lacfile.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
lacfile.o: /usr/include/endian.h /usr/include/bits/endian.h
lacfile.o: /usr/include/sys/select.h /usr/include/bits/select.h
lacfile.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
lacfile.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
lacfile.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
lacfile.o: /usr/include/bits/posix2_lim.h
laclose.o: la.local.h ../include/c_env.h ../include/localenv.h
laclose.o: /usr/include/stdio.h /usr/include/features.h
laclose.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laclose.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
laclose.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
laclose.o: /usr/include/bits/types.h /usr/include/libio.h
laclose.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
laclose.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
laclose.o: /usr/include/endian.h /usr/include/bits/endian.h
laclose.o: /usr/include/sys/select.h /usr/include/bits/select.h
laclose.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
laclose.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
laclose.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
laclose.o: /usr/include/bits/posix2_lim.h
ladeb.o: la.local.h ../include/c_env.h ../include/localenv.h
ladeb.o: /usr/include/stdio.h /usr/include/features.h
ladeb.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
ladeb.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
ladeb.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
ladeb.o: /usr/include/bits/types.h /usr/include/libio.h
ladeb.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
ladeb.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
ladeb.o: /usr/include/endian.h /usr/include/bits/endian.h
ladeb.o: /usr/include/sys/select.h /usr/include/bits/select.h
ladeb.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
ladeb.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
ladeb.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
ladeb.o: /usr/include/bits/posix2_lim.h
laerr.o: la.local.h ../include/c_env.h ../include/localenv.h
laerr.o: /usr/include/stdio.h /usr/include/features.h
laerr.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laerr.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
laerr.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
laerr.o: /usr/include/bits/types.h /usr/include/libio.h
laerr.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
laerr.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
laerr.o: /usr/include/endian.h /usr/include/bits/endian.h
laerr.o: /usr/include/sys/select.h /usr/include/bits/select.h
laerr.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
laerr.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
laerr.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
laerr.o: /usr/include/bits/posix2_lim.h
lafrpl.o: la.local.h ../include/c_env.h ../include/localenv.h
lafrpl.o: /usr/include/stdio.h /usr/include/features.h
lafrpl.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lafrpl.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
lafrpl.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
lafrpl.o: /usr/include/bits/types.h /usr/include/libio.h
lafrpl.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
lafrpl.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
lafrpl.o: /usr/include/endian.h /usr/include/bits/endian.h
lafrpl.o: /usr/include/sys/select.h /usr/include/bits/select.h
lafrpl.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
lafrpl.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
lafrpl.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
lafrpl.o: /usr/include/bits/posix2_lim.h
lalcnt.o: la.local.h ../include/c_env.h ../include/localenv.h
lalcnt.o: /usr/include/stdio.h /usr/include/features.h
lalcnt.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalcnt.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
lalcnt.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
lalcnt.o: /usr/include/bits/types.h /usr/include/libio.h
lalcnt.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
lalcnt.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
lalcnt.o: /usr/include/endian.h /usr/include/bits/endian.h
lalcnt.o: /usr/include/sys/select.h /usr/include/bits/select.h
lalcnt.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
lalcnt.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
lalcnt.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
lalcnt.o: /usr/include/bits/posix2_lim.h
lalcol.o: la.local.h ../include/c_env.h ../include/localenv.h
lalcol.o: /usr/include/stdio.h /usr/include/features.h
lalcol.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalcol.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
lalcol.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
lalcol.o: /usr/include/bits/types.h /usr/include/libio.h
lalcol.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
lalcol.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
lalcol.o: /usr/include/endian.h /usr/include/bits/endian.h
lalcol.o: /usr/include/sys/select.h /usr/include/bits/select.h
lalcol.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
lalcol.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
lalcol.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
lalcol.o: /usr/include/bits/posix2_lim.h
lalcopy.o: la.local.h ../include/c_env.h ../include/localenv.h
lalcopy.o: /usr/include/stdio.h /usr/include/features.h
lalcopy.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalcopy.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
lalcopy.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
lalcopy.o: /usr/include/bits/types.h /usr/include/libio.h
lalcopy.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
lalcopy.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
lalcopy.o: /usr/include/endian.h /usr/include/bits/endian.h
lalcopy.o: /usr/include/sys/select.h /usr/include/bits/select.h
lalcopy.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
lalcopy.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
lalcopy.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
lalcopy.o: /usr/include/bits/posix2_lim.h
laldel.o: la.local.h ../include/c_env.h ../include/localenv.h
laldel.o: /usr/include/stdio.h /usr/include/features.h
laldel.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laldel.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
laldel.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
laldel.o: /usr/include/bits/types.h /usr/include/libio.h
laldel.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
laldel.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
laldel.o: /usr/include/endian.h /usr/include/bits/endian.h
laldel.o: /usr/include/sys/select.h /usr/include/bits/select.h
laldel.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
laldel.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
laldel.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
laldel.o: /usr/include/bits/posix2_lim.h
lalflush.o: la.local.h ../include/c_env.h ../include/localenv.h
lalflush.o: /usr/include/stdio.h /usr/include/features.h
lalflush.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalflush.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
lalflush.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
lalflush.o: /usr/include/bits/types.h /usr/include/libio.h
lalflush.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
lalflush.o: /usr/include/string.h /usr/include/sys/types.h
lalflush.o: /usr/include/time.h /usr/include/endian.h
lalflush.o: /usr/include/bits/endian.h /usr/include/sys/select.h
lalflush.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
lalflush.o: /usr/include/sys/sysmacros.h la.h ../ff3/ff.h
lalflush.o: /usr/include/limits.h /usr/include/bits/posix1_lim.h
lalflush.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
lalflush.o: /usr/include/bits/posix2_lim.h /usr/include/errno.h
lalflush.o: /usr/include/bits/errno.h /usr/include/linux/errno.h
lalflush.o: /usr/include/asm/errno.h /usr/include/signal.h
lalflush.o: /usr/include/bits/signum.h /usr/include/bits/siginfo.h
lalflush.o: /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h
lalflush.o: /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h
lalget.o: la.local.h ../include/c_env.h ../include/localenv.h
lalget.o: /usr/include/stdio.h /usr/include/features.h
lalget.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalget.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
lalget.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
lalget.o: /usr/include/bits/types.h /usr/include/libio.h
lalget.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
lalget.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
lalget.o: /usr/include/endian.h /usr/include/bits/endian.h
lalget.o: /usr/include/sys/select.h /usr/include/bits/select.h
lalget.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
lalget.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
lalget.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
lalget.o: /usr/include/bits/posix2_lim.h
lalink.o: la.local.h ../include/c_env.h ../include/localenv.h
lalink.o: /usr/include/stdio.h /usr/include/features.h
lalink.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalink.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
lalink.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
lalink.o: /usr/include/bits/types.h /usr/include/libio.h
lalink.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
lalink.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
lalink.o: /usr/include/endian.h /usr/include/bits/endian.h
lalink.o: /usr/include/sys/select.h /usr/include/bits/select.h
lalink.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
lalink.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
lalink.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
lalink.o: /usr/include/bits/posix2_lim.h
lalins.o: la.local.h ../include/c_env.h ../include/localenv.h
lalins.o: /usr/include/stdio.h /usr/include/features.h
lalins.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalins.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
lalins.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
lalins.o: /usr/include/bits/types.h /usr/include/libio.h
lalins.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
lalins.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
lalins.o: /usr/include/endian.h /usr/include/bits/endian.h
lalins.o: /usr/include/sys/select.h /usr/include/bits/select.h
lalins.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
lalins.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
lalins.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
lalins.o: /usr/include/bits/posix2_lim.h
lalpnt.o: la.local.h ../include/c_env.h ../include/localenv.h
lalpnt.o: /usr/include/stdio.h /usr/include/features.h
lalpnt.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalpnt.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
lalpnt.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
lalpnt.o: /usr/include/bits/types.h /usr/include/libio.h
lalpnt.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
lalpnt.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
lalpnt.o: /usr/include/endian.h /usr/include/bits/endian.h
lalpnt.o: /usr/include/sys/select.h /usr/include/bits/select.h
lalpnt.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
lalpnt.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
lalpnt.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
lalpnt.o: /usr/include/bits/posix2_lim.h
lalrpl.o: la.local.h ../include/c_env.h ../include/localenv.h
lalrpl.o: /usr/include/stdio.h /usr/include/features.h
lalrpl.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalrpl.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
lalrpl.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
lalrpl.o: /usr/include/bits/types.h /usr/include/libio.h
lalrpl.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
lalrpl.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
lalrpl.o: /usr/include/endian.h /usr/include/bits/endian.h
lalrpl.o: /usr/include/sys/select.h /usr/include/bits/select.h
lalrpl.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
lalrpl.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
lalrpl.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
lalrpl.o: /usr/include/bits/posix2_lim.h
lalrsize.o: la.local.h ../include/c_env.h ../include/localenv.h
lalrsize.o: /usr/include/stdio.h /usr/include/features.h
lalrsize.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalrsize.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
lalrsize.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
lalrsize.o: /usr/include/bits/types.h /usr/include/libio.h
lalrsize.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
lalrsize.o: /usr/include/string.h /usr/include/sys/types.h
lalrsize.o: /usr/include/time.h /usr/include/endian.h
lalrsize.o: /usr/include/bits/endian.h /usr/include/sys/select.h
lalrsize.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
lalrsize.o: /usr/include/sys/sysmacros.h la.h ../ff3/ff.h
lalrsize.o: /usr/include/limits.h /usr/include/bits/posix1_lim.h
lalrsize.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
lalrsize.o: /usr/include/bits/posix2_lim.h
lalseek.o: la.local.h ../include/c_env.h ../include/localenv.h
lalseek.o: /usr/include/stdio.h /usr/include/features.h
lalseek.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalseek.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
lalseek.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
lalseek.o: /usr/include/bits/types.h /usr/include/libio.h
lalseek.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
lalseek.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
lalseek.o: /usr/include/endian.h /usr/include/bits/endian.h
lalseek.o: /usr/include/sys/select.h /usr/include/bits/select.h
lalseek.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
lalseek.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
lalseek.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
lalseek.o: /usr/include/bits/posix2_lim.h
lalwsize.o: la.local.h ../include/c_env.h ../include/localenv.h
lalwsize.o: /usr/include/stdio.h /usr/include/features.h
lalwsize.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
lalwsize.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
lalwsize.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
lalwsize.o: /usr/include/bits/types.h /usr/include/libio.h
lalwsize.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
lalwsize.o: /usr/include/string.h /usr/include/sys/types.h
lalwsize.o: /usr/include/time.h /usr/include/endian.h
lalwsize.o: /usr/include/bits/endian.h /usr/include/sys/select.h
lalwsize.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
lalwsize.o: /usr/include/sys/sysmacros.h la.h ../ff3/ff.h
lalwsize.o: /usr/include/limits.h /usr/include/bits/posix1_lim.h
lalwsize.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
lalwsize.o: /usr/include/bits/posix2_lim.h
laopen.o: la.local.h ../include/c_env.h ../include/localenv.h
laopen.o: /usr/include/stdio.h /usr/include/features.h
laopen.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laopen.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
laopen.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
laopen.o: /usr/include/bits/types.h /usr/include/libio.h
laopen.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
laopen.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
laopen.o: /usr/include/endian.h /usr/include/bits/endian.h
laopen.o: /usr/include/sys/select.h /usr/include/bits/select.h
laopen.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
laopen.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
laopen.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
laopen.o: /usr/include/bits/posix2_lim.h /usr/include/sys/stat.h
laopen.o: /usr/include/bits/stat.h /usr/include/sys/resource.h
laopen.o: /usr/include/bits/resource.h /usr/include/asm/resource.h
laopen.o: /usr/include/bits/time.h
laother.o: la.local.h ../include/c_env.h ../include/localenv.h
laother.o: /usr/include/stdio.h /usr/include/features.h
laother.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
laother.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stddef.h
laother.o: /usr/lib/gcc-lib/i386-redhat-linux/egcs-2.91.66/include/stdarg.h
laother.o: /usr/include/bits/types.h /usr/include/libio.h
laother.o: /usr/include/_G_config.h /usr/include/bits/stdio_lim.h
laother.o: /usr/include/string.h /usr/include/sys/types.h /usr/include/time.h
laother.o: /usr/include/endian.h /usr/include/bits/endian.h
laother.o: /usr/include/sys/select.h /usr/include/bits/select.h
laother.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h la.h
laother.o: ../ff3/ff.h /usr/include/limits.h /usr/include/bits/posix1_lim.h
laother.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
laother.o: /usr/include/bits/posix2_lim.h
