#
#       MAKEFILE FOR RAND "LA" LINE-ACCESS I/O PACKAGE
#
ARFLAGS = -r
# CFLAGS = -O -I. -I../ff3 -I../include
CFLAGS = -I. -I../ff3 -I../include -g

ALL=libla.a
SRCS=   laabort.c laadv.c   laalign.c lablank.c labreak.c labsize.c \
	lacfile.c laclose.c ladeb.c   laerr.c   lafrpl.c \
	laint.c   lalcnt.c  lalcol.c  lalcopy.c laldel.c  lalflush.c \
	lalget.c  lalink.c  lalins.c  lalpnt.c  lalrpl.c  lalrsize.c \
	lalseek.c lalwsize.c laopen.c laother.c

OBJS=   laabort.o laadv.o   laalign.o lablank.o labreak.o labsize.o \
	lacfile.o laclose.o ladeb.o   laerr.o   lafrpl.o \
	laint.o   lalcnt.o  lalcol.o  lalcopy.o laldel.o  lalflush.o \
	lalget.o  lalink.o  lalins.o  lalpnt.o  lalrpl.o  lalrsize.o \
	lalseek.o lalwsize.o laopen.o laother.o

$(ALL) : $(OBJS)
	$(AR) $(ARFLAGS) $@ $(OBJS)

clean:
	rm -f $(OBJS) $(ALL)  ,* .e?1 .e?1.* core *.bak *.BAK *~ \#*

depend:
	makedepend -- $(CFLAGS) -- $(SRCS)

# DO NOT DELETE THIS LINE -- make depend depends on it.

laabort.o: la.local.h ../include/c_env.h ../include/localenv.h
laabort.o: /usr/include/stdio.h /usr/include/standards.h
laabort.o: /usr/include/va_list.h /usr/include/sys/types.h
laabort.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
laabort.o: /usr/include/sys/limits.h /usr/include/float.h
laabort.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
laadv.o: la.local.h ../include/c_env.h ../include/localenv.h
laadv.o: /usr/include/stdio.h /usr/include/standards.h /usr/include/va_list.h
laadv.o: /usr/include/sys/types.h /usr/include/sys/inttypes.h
laadv.o: /usr/include/sys/m_types.h /usr/include/sys/limits.h
laadv.o: /usr/include/float.h /usr/include/string.h la.h ../ff3/ff.h
laadv.o: /usr/include/limits.h
laalign.o: la.local.h ../include/c_env.h ../include/localenv.h
laalign.o: /usr/include/stdio.h /usr/include/standards.h
laalign.o: /usr/include/va_list.h /usr/include/sys/types.h
laalign.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
laalign.o: /usr/include/sys/limits.h /usr/include/float.h
laalign.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
lablank.o: la.local.h ../include/c_env.h ../include/localenv.h
lablank.o: /usr/include/stdio.h /usr/include/standards.h
lablank.o: /usr/include/va_list.h /usr/include/sys/types.h
lablank.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
lablank.o: /usr/include/sys/limits.h /usr/include/float.h
lablank.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
labreak.o: la.local.h ../include/c_env.h ../include/localenv.h
labreak.o: /usr/include/stdio.h /usr/include/standards.h
labreak.o: /usr/include/va_list.h /usr/include/sys/types.h
labreak.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
labreak.o: /usr/include/sys/limits.h /usr/include/float.h
labreak.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
labsize.o: la.local.h ../include/c_env.h ../include/localenv.h
labsize.o: /usr/include/stdio.h /usr/include/standards.h
labsize.o: /usr/include/va_list.h /usr/include/sys/types.h
labsize.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
labsize.o: /usr/include/sys/limits.h /usr/include/float.h
labsize.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
lacfile.o: la.local.h ../include/c_env.h ../include/localenv.h
lacfile.o: /usr/include/stdio.h /usr/include/standards.h
lacfile.o: /usr/include/va_list.h /usr/include/sys/types.h
lacfile.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
lacfile.o: /usr/include/sys/limits.h /usr/include/float.h
lacfile.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
laclose.o: la.local.h ../include/c_env.h ../include/localenv.h
laclose.o: /usr/include/stdio.h /usr/include/standards.h
laclose.o: /usr/include/va_list.h /usr/include/sys/types.h
laclose.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
laclose.o: /usr/include/sys/limits.h /usr/include/float.h
laclose.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
ladeb.o: la.local.h ../include/c_env.h ../include/localenv.h
ladeb.o: /usr/include/stdio.h /usr/include/standards.h /usr/include/va_list.h
ladeb.o: /usr/include/sys/types.h /usr/include/sys/inttypes.h
ladeb.o: /usr/include/sys/m_types.h /usr/include/sys/limits.h
ladeb.o: /usr/include/float.h /usr/include/string.h la.h ../ff3/ff.h
ladeb.o: /usr/include/limits.h
laerr.o: la.local.h ../include/c_env.h ../include/localenv.h
laerr.o: /usr/include/stdio.h /usr/include/standards.h /usr/include/va_list.h
laerr.o: /usr/include/sys/types.h /usr/include/sys/inttypes.h
laerr.o: /usr/include/sys/m_types.h /usr/include/sys/limits.h
laerr.o: /usr/include/float.h /usr/include/string.h la.h ../ff3/ff.h
laerr.o: /usr/include/limits.h
lafrpl.o: la.local.h ../include/c_env.h ../include/localenv.h
lafrpl.o: /usr/include/stdio.h /usr/include/standards.h
lafrpl.o: /usr/include/va_list.h /usr/include/sys/types.h
lafrpl.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
lafrpl.o: /usr/include/sys/limits.h /usr/include/float.h
lafrpl.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
lalcnt.o: la.local.h ../include/c_env.h ../include/localenv.h
lalcnt.o: /usr/include/stdio.h /usr/include/standards.h
lalcnt.o: /usr/include/va_list.h /usr/include/sys/types.h
lalcnt.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
lalcnt.o: /usr/include/sys/limits.h /usr/include/float.h
lalcnt.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
lalcol.o: la.local.h ../include/c_env.h ../include/localenv.h
lalcol.o: /usr/include/stdio.h /usr/include/standards.h
lalcol.o: /usr/include/va_list.h /usr/include/sys/types.h
lalcol.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
lalcol.o: /usr/include/sys/limits.h /usr/include/float.h
lalcol.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
lalcopy.o: la.local.h ../include/c_env.h ../include/localenv.h
lalcopy.o: /usr/include/stdio.h /usr/include/standards.h
lalcopy.o: /usr/include/va_list.h /usr/include/sys/types.h
lalcopy.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
lalcopy.o: /usr/include/sys/limits.h /usr/include/float.h
lalcopy.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
laldel.o: la.local.h ../include/c_env.h ../include/localenv.h
laldel.o: /usr/include/stdio.h /usr/include/standards.h
laldel.o: /usr/include/va_list.h /usr/include/sys/types.h
laldel.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
laldel.o: /usr/include/sys/limits.h /usr/include/float.h
laldel.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
lalflush.o: la.local.h ../include/c_env.h ../include/localenv.h
lalflush.o: /usr/include/stdio.h /usr/include/standards.h
lalflush.o: /usr/include/va_list.h /usr/include/sys/types.h
lalflush.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
lalflush.o: /usr/include/sys/limits.h /usr/include/float.h
lalflush.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
lalflush.o: /usr/include/errno.h /usr/include/signal.h
lalflush.o: /usr/include/sys/signal.h /usr/include/sys/context.h
lalflush.o: /usr/include/sys/m_param.h /usr/include/sys/mstsave.h
lalget.o: la.local.h ../include/c_env.h ../include/localenv.h
lalget.o: /usr/include/stdio.h /usr/include/standards.h
lalget.o: /usr/include/va_list.h /usr/include/sys/types.h
lalget.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
lalget.o: /usr/include/sys/limits.h /usr/include/float.h
lalget.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
lalink.o: la.local.h ../include/c_env.h ../include/localenv.h
lalink.o: /usr/include/stdio.h /usr/include/standards.h
lalink.o: /usr/include/va_list.h /usr/include/sys/types.h
lalink.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
lalink.o: /usr/include/sys/limits.h /usr/include/float.h
lalink.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
lalins.o: la.local.h ../include/c_env.h ../include/localenv.h
lalins.o: /usr/include/stdio.h /usr/include/standards.h
lalins.o: /usr/include/va_list.h /usr/include/sys/types.h
lalins.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
lalins.o: /usr/include/sys/limits.h /usr/include/float.h
lalins.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
lalpnt.o: la.local.h ../include/c_env.h ../include/localenv.h
lalpnt.o: /usr/include/stdio.h /usr/include/standards.h
lalpnt.o: /usr/include/va_list.h /usr/include/sys/types.h
lalpnt.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
lalpnt.o: /usr/include/sys/limits.h /usr/include/float.h
lalpnt.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
lalrpl.o: la.local.h ../include/c_env.h ../include/localenv.h
lalrpl.o: /usr/include/stdio.h /usr/include/standards.h
lalrpl.o: /usr/include/va_list.h /usr/include/sys/types.h
lalrpl.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
lalrpl.o: /usr/include/sys/limits.h /usr/include/float.h
lalrpl.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
lalrsize.o: la.local.h ../include/c_env.h ../include/localenv.h
lalrsize.o: /usr/include/stdio.h /usr/include/standards.h
lalrsize.o: /usr/include/va_list.h /usr/include/sys/types.h
lalrsize.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
lalrsize.o: /usr/include/sys/limits.h /usr/include/float.h
lalrsize.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
lalseek.o: la.local.h ../include/c_env.h ../include/localenv.h
lalseek.o: /usr/include/stdio.h /usr/include/standards.h
lalseek.o: /usr/include/va_list.h /usr/include/sys/types.h
lalseek.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
lalseek.o: /usr/include/sys/limits.h /usr/include/float.h
lalseek.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
lalwsize.o: la.local.h ../include/c_env.h ../include/localenv.h
lalwsize.o: /usr/include/stdio.h /usr/include/standards.h
lalwsize.o: /usr/include/va_list.h /usr/include/sys/types.h
lalwsize.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
lalwsize.o: /usr/include/sys/limits.h /usr/include/float.h
lalwsize.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
laopen.o: la.local.h ../include/c_env.h ../include/localenv.h
laopen.o: /usr/include/stdio.h /usr/include/standards.h
laopen.o: /usr/include/va_list.h /usr/include/sys/types.h
laopen.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
laopen.o: /usr/include/sys/limits.h /usr/include/float.h
laopen.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
laopen.o: /usr/include/sys/stat.h /usr/include/sys/mode.h
laopen.o: /usr/include/sys/resource.h /usr/include/sys/time.h
laother.o: la.local.h ../include/c_env.h ../include/localenv.h
laother.o: /usr/include/stdio.h /usr/include/standards.h
laother.o: /usr/include/va_list.h /usr/include/sys/types.h
laother.o: /usr/include/sys/inttypes.h /usr/include/sys/m_types.h
laother.o: /usr/include/sys/limits.h /usr/include/float.h
laother.o: /usr/include/string.h la.h ../ff3/ff.h /usr/include/limits.h
